### PR TITLE
Add Variable replace possibility

### PR DESCRIPTION
**Pull request by git001**
Solve https://github.com/abiosoft/caddy-exec/issues/7

### CODE REVIEW

**Review by yroc92 — APPROVED** [review]

**Comment by richcorbs** [comment]
This looks sooooo useful to me. Any update?

**Comment by git001** [comment]
Well I have add this feature to my fork https://github.com/git001/caddy-exec as I don't know if the PR will be merged.

**Comment by richcorbs** [comment]
Thanks @git001! I'm new to caddy and go. I have go built with the abiosoft version of caddy-exec. How can I build it with your version?

**Comment by git001** [comment]
@richcorbs  as @yroc92 written can you create your own caddy version with [xcaddy](https://github.com/caddyserver/xcaddy) you can add with `--with ... ` any further module you want from the https://caddyserver.com/download list.

**Comment by richcorbs** [comment]
Thank you both for the help.

What's the syntax? This is what I'm trying:

```
http://localhost {
         route /check {
                 exec /check /bin/ls /var/www/{query domain} {
                         foreground true
                         status 404 on error
                 }
         }
}
```

When I curl that route with `?domain=abc.com` I get this error and the placeholders aren't interpolated properly:

```
2022/12/13 04:55:28.937	ERROR	http.handlers.exec.exit		{"command": ["exec", "/bin/ls", "/var/www/{query", "domain}"], "duration": 0.000353293, "error": "exec: \"exec\": executable file not found in $PATH"}
```

**Comment by git001** [comment]
Please try to use `"/var/www/{query domain}"`  it's just the same as every other placeholder usage.  
https://caddyserver.com/docs/conventions#placeholders

**Comment by richcorbs** [comment]
Progress! I tried using `query.domain` instead of `query domain` and it seems to have parsed the command properly! Thanks for that! The output on the server is now:

```
2022/12/13 10:54:04.997	ERROR	http.handlers.exec.exit		{"command": ["exec", "/bin/ls", "/var/www/abc.com"], "duration": 0.000318644, "error": "exec: \"exec\": executable file not found in $PATH"}
```

I'm still getting `"error": "exec: \"exec\": executable file not found in $PATH"`. Does this imply that there is something wrong with my go environment?

**Comment by git001** [comment]
well `exec` is wrong here. just use /bin/ls.

**Comment by richcorbs** [comment]
I don't understand. I'm not adding exec anywhere. Exec only shows up as the
directive in the config.

**Comment by richcorbs** [comment]
Is it possible that caddy-exec is adding in "exec" somehow?

Do you have a working configuration you could share with me?

**Comment by richcorbs** [comment]
I got around the `exec` issue in the OS by linking `exec` to `/bin/sh` and it works. Kind of.

Whatever querystring is passed the first time is what it remembers for every execution after that. I was hoping it might be dynamic on every request.

**Comment by git001** [comment]
> I had an idea. Is this only supported in the `.json` config file and not in a `Caddyfile`?

Yes I have tested it only with `json` version.

**Comment by abiosoft** [comment]
> @abiosoft Any chance of getting this merged? It would be extremely helpful to be able to replace `{placeholders}` in the exec command/args.

Done ✅

**Comment by Omicron7** [comment]
@abiosoft Thanks

**Pull request merged**
