### PR TITLE
caddyfile: Implement global option support

### PR DESCRIPTION
**Pull request by francislavoie**
See https://github.com/caddyserver/caddy/pull/3990 for the change in Caddy that makes this possible.

To try this, I had to build this from a temp directory with a `go.mod` like this, to replace both the caddy and caddy-exec modules with local copies, so you would need to do the same to try it out until the upstream PR is merged/released.

```
module caddy

go 1.15

replace github.com/caddyserver/caddy/v2 => ../caddy

replace github.com/abiosoft/caddy-exec => ../caddy-exec

require (
        github.com/abiosoft/caddy-exec v0.0.0-00010101000000-000000000000
        github.com/caddyserver/caddy/v2 v2.3.0
)
```

Also updated the `go.mod` to the latest versions.

Here's the adapt:

Caddyfile
```
{
        exec {
                command curl.exe "https://google.com" {
                        at startup
                }
                command echo {
                        args "foobar"
                        at startup
                }
                command hugo {
                        args "generate" "--destination=/home/user/site/public"
                        directory /foo/bar
                        at startup
                        foreground
                        timeout 10s
                }
        }
}
```

👇 

```json
{
        "apps": {
                "exec": {
                        "commands": [
                                {
                                        "command": "curl.exe",
                                        "args": [
                                                "https://google.com"
                                        ],
                                        "at": [
                                                "startup"
                                        ]
                                },
                                {
                                        "command": "echo",
                                        "args": [
                                                "foobar"
                                        ],
                                        "at": [
                                                "startup"
                                        ]
                                },
                                {
                                        "command": "hugo",
                                        "args": [
                                                "generate",
                                                "--destination=/home/user/site/public"
                                        ],
                                        "directory": "/foo/bar",
                                        "foreground": true,
                                        "timeout": "10s",
                                        "at": [
                                                "startup"
                                        ]
                                }
                        ]
                }
        }
}
```

### CODE REVIEW

**Comment by abiosoft** [comment]
Thank you very much for this PR and your work on getting Caddy to support this. 
I think I'll leave this open until the upstream feature is merged.

**Comment by francislavoie** [comment]
Alright the upstream PR is merged, and will land in v2.4.0, or the next beta! 🎉

**Comment by francislavoie** [comment]
@abiosoft I forgot - should probably update the `go.mod` to target `v2.4.0-beta.1` cause that's the first version with this feature in it.

**Comment by abiosoft** [comment]
@francislavoie yeah, I clicked on merge before thinking of that. I'll update it.

Thanks.

**Pull request merged**
